package CourseRegistrationApp;


/**
* CourseRegistrationApp/CoursesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcrs.idl
* Wednesday, October 31, 2018 1:21:53 o'clock PM EDT
*/

public final class CoursesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public CoursesHolder ()
  {
  }

  public CoursesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CourseRegistrationApp.CoursesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CourseRegistrationApp.CoursesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CourseRegistrationApp.CoursesHelper.type ();
  }

}
