package CourseRegistrationApp;


/**
* CourseRegistrationApp/Course.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcrs.idl
* Sunday, November 4, 2018 3:43:08 o'clock PM EST
*/

public final class Course implements org.omg.CORBA.portable.IDLEntity
{
  public String course_name = null;
  public String term = null;
  public String course_id = null;
  public short capacity = (short)0;
  public String enrolledStudentId[] = null;

  public Course ()
  {
  } // ctor

  public Course (String _course_name, String _term, String _course_id, short _capacity, String[] _enrolledStudentId)
  {
    course_name = _course_name;
    term = _term;
    course_id = _course_id;
    capacity = _capacity;
    enrolledStudentId = _enrolledStudentId;
  } // ctor

} // class Course
