package CourseRegistrationApp;


/**
* CourseRegistrationApp/Seats_AvailableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcrs.idl
* Sunday, October 28, 2018 7:53:25 o'clock PM EDT
*/

public final class Seats_AvailableHolder implements org.omg.CORBA.portable.Streamable
{
  public short value[] = null;

  public Seats_AvailableHolder ()
  {
  }

  public Seats_AvailableHolder (short[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CourseRegistrationApp.Seats_AvailableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CourseRegistrationApp.Seats_AvailableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CourseRegistrationApp.Seats_AvailableHelper.type ();
  }

}
