package CourseRegistrationApp;


/**
* CourseRegistrationApp/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcrs.idl
* Sunday, November 4, 2018 3:43:09 o'clock PM EST
*/

public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
