package CourseRegistrationApp;


/**
* CourseRegistrationApp/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcrs.idl
* Sunday, October 28, 2018 7:53:25 o'clock PM EDT
*/

public interface ServerOperations 
{
  boolean advisor_exists (String advisor_id, String dept);
  boolean student_exists (String student_id, String dept);
  String enroll (String courseId, String studentId, String term, String dept);
  String addCourse (String advisor_id, String course_id, String course_name, String term, String dept, short capacity);
  String dropCourse (String advisor_id, String course_id, String term, String dept);
  String removeCourse (String advisor_id, String course_id, String term, String dept);
  boolean listCourseAvailability (String advisor_id, String term, String dept, CourseRegistrationApp.TermHolder theTerm);
  boolean getClassSchedule (String studentId, CourseRegistrationApp.TermHolder term, CourseRegistrationApp.CoursesHolder courses);
} // interface ServerOperations
