package CourseRegistrationApp;


/**
* CourseRegistrationApp/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcrs.idl
* Sunday, October 28, 2018 7:53:25 o'clock PM EDT
*/

public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
