package CourseRegistrationApp;


/**
* CourseRegistrationApp/TermHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcrs.idl
* Sunday, October 28, 2018 7:53:25 o'clock PM EDT
*/

public final class TermHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public TermHolder ()
  {
  }

  public TermHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CourseRegistrationApp.TermHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CourseRegistrationApp.TermHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CourseRegistrationApp.TermHelper.type ();
  }

}
